### PR TITLE
Doc

### PR DESCRIPTION
**Pull request by vaibhavgarg11**

### CODE REVIEW

**Comment by SebastinSanty** [comment]
@vaibhavgarg11 Can you describe the changes here?

**Comment by vaibhavgarg11** [comment]
I only added some lines at the start of index.js and pushed them. For some reason it shows the previous commit made under the message of final commit was made again.

**Comment by SebastinSanty** [comment]
Yes, because you are on the same branch. Checkout to a different branch and submit a PR.

**Comment by prasadtalasila** [comment]
@vaibhavgarg11 Please rebase your dev branch. The problem shoukd go away. Then open a fresh PR.

**Pull request closed without merging**
