### PR TITLE
Doc

### PR DESCRIPTION
**Pull request by vaibhavgarg11**
###Description of the Change
Did documentation for 3 modules rev.js, init.js, git.js and did some changes to the documentation of help.js to increase readability in the html page 

### Benefits
Added the documentation

### Possible Drawbacks
The html pages of the documentation do not display content in an orderly fashion

### CODE REVIEW

**Comment by SebastinSanty** [comment]
Regarding `out` in `.gitignore` : I'll wait for a confirmation from @prasadtalasila to check which method we'll go about: `gh-pages` or `out` in master itself.

**Comment by SebastinSanty** [comment]
@vaibhavgarg11 Also your `.gitignore` file is conflicting. Please resolve that :)

**Comment by prasadtalasila** [comment]
We will use gh-pages for website content. For now, the generated content can be manually pushed to gh-pages branch. Later we will automate the doc generation step as well.

**Comment by prasadtalasila** [comment]
The code looks good. Please rebase to a single commit. @sebastinsanty is requested to verify the correctness of the comments.

**Comment by prasadtalasila** [comment]
@vaibhavgarg11 The website content directory _out_ is still included in the commit. Please remove the website content.
The way to track the reduction in code coverage is to track the files that changed in your commit history. The coverage was at 5% yesterday. So only a few changes must have taken place.

After making necessary changes, do rebase to a single commit.

**Comment by prasadtalasila** [comment]
The commits to track for reduction in code coverage are 7bbce54 (coverage reduced in this commit) and 2926773.

**Comment by prasadtalasila** [comment]
@vaibhavgarg11 good to retain the code coverage. Is it just the exclusion of out/ directory or something else changed as well?

@SebastinSanty please confirm the correctness of comments and then merge the PR.

**Comment by prasadtalasila** [comment]
Good work @vaibhavgarg11

**Pull request merged**
